### ISSUE TITLE
multiple initial commit dates

### ISSUE THREAD

**Issue by passsy** [passsy/gradle-gitVersioner-plugin#2]
version 0.3.0

```
Caused by: java.lang.NumberFormatException: For input string: "1500618776
1481047303"
        at com.pascalwelsch.gitversioner.ShellGitInfoExtractor$initialCommitDate$2.invoke(ShellGitInfoExtractor.kt:46)
        at com.pascalwelsch.gitversioner.ShellGitInfoExtractor$initialCommitDate$2.invoke(ShellGitInfoExtractor.kt:21)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at com.pascalwelsch.gitversioner.ShellGitInfoExtractor.getInitialCommitDate(ShellGitInfoExtractor.kt)
        at com.pascalwelsch.gitversioner.GitVersioner$timeComponent$2.invoke(GitVersioner.kt:134)
        at com.pascalwelsch.gitversioner.GitVersioner$timeComponent$2.invoke(GitVersioner.kt:12)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at com.pascalwelsch.gitversioner.GitVersioner.getTimeComponent(GitVersioner.kt)
        at com.pascalwelsch.gitversioner.GitVersioner$versionCode$2.invoke(GitVersioner.kt:52)
        at com.pascalwelsch.gitversioner.GitVersioner$versionCode$2.invoke(GitVersioner.kt:12)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
        at com.pascalwelsch.gitversioner.GitVersioner.getVersionCode(GitVersioner.kt)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
        at com.pascalwelsch.gitversioner.GitVersioner_Decorated.getProperty(Unknown Source)
```

**Comment by passsy** [comment]
fixed with #3
